// Auto-generated by scripts/generate-icon-sprite.js
// DO NOT EDIT MANUALLY - Run 'npm run build:sprite' to regenerate

import { ICON_SIZE } from '../lib/appConfig';

export interface IconSpriteCoords {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const ICON_SPRITE_PATH = '/icon-sprite.png';

// Sprite atlas dimensions for background-size scaling
export const SPRITE_COLUMNS = 16;
export const SPRITE_ICON_SIZE = 32;
export const SPRITE_PADDING = 2;
export const SPRITE_WIDTH = 544;
export const SPRITE_HEIGHT = 374;

export const ICON_SPRITE_METADATA: Record<string, IconSpriteCoords> = {
  "MapIconAircraftDepot": {
    "x": 0,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftDepotColonial": {
    "x": 34,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftDepotWarden": {
    "x": 68,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftFactory": {
    "x": 102,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftFactoryColonial": {
    "x": 136,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftFactoryWarden": {
    "x": 170,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRadar": {
    "x": 204,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRadarColonial": {
    "x": 238,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRadarWarden": {
    "x": 272,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT1": {
    "x": 306,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT1Colonial": {
    "x": 340,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT1Warden": {
    "x": 374,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT2": {
    "x": 408,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT2Colonial": {
    "x": 442,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAircraftRunwayT2Warden": {
    "x": 476,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAmmoFactory": {
    "x": 510,
    "y": 0,
    "width": 32,
    "height": 32
  },
  "MapIconAmmoFactoryColonial": {
    "x": 0,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconAmmoFactoryWarden": {
    "x": 34,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCivicCenter": {
    "x": 68,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCivicCenterColonial": {
    "x": 102,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCivicCenterWarden": {
    "x": 136,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoal": {
    "x": 170,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoalColonial": {
    "x": 204,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoalWarden": {
    "x": 238,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoastalGun": {
    "x": 272,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoastalGunColonial": {
    "x": 306,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconCoastalGunWarden": {
    "x": 340,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponentMine": {
    "x": 374,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponentMineColonial": {
    "x": 408,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponentMineWarden": {
    "x": 442,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponents": {
    "x": 476,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponentsColonial": {
    "x": 510,
    "y": 34,
    "width": 32,
    "height": 32
  },
  "MapIconComponentsWarden": {
    "x": 0,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconConstructionYard": {
    "x": 34,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconConstructionYardColonial": {
    "x": 68,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconConstructionYardWarden": {
    "x": 102,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFacilityMineOilRig": {
    "x": 136,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFacilityMineOilRigColonial": {
    "x": 170,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFacilityMineOilRigWarden": {
    "x": 204,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFactory": {
    "x": 238,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFactoryColonial": {
    "x": 272,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFactoryWarden": {
    "x": 306,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFort": {
    "x": 340,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFortColonial": {
    "x": 374,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconFortWarden": {
    "x": 408,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase1": {
    "x": 442,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase1Colonial": {
    "x": 476,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase1Warden": {
    "x": 510,
    "y": 68,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase2": {
    "x": 0,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase2Colonial": {
    "x": 34,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase2Warden": {
    "x": 68,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase3": {
    "x": 102,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase3Colonial": {
    "x": 136,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconForwardBase3Warden": {
    "x": 170,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconFuel": {
    "x": 204,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconFuelColonial": {
    "x": 238,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconFuelWarden": {
    "x": 272,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconIntelCenter": {
    "x": 306,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconIntelCenterColonial": {
    "x": 340,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconIntelCenterWarden": {
    "x": 374,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconKeep": {
    "x": 408,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconKeepColonial": {
    "x": 442,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconKeepWarden": {
    "x": 476,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconManufacturing": {
    "x": 510,
    "y": 102,
    "width": 32,
    "height": 32
  },
  "MapIconManufacturingColonial": {
    "x": 0,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconManufacturingWarden": {
    "x": 34,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMassProductionFactory": {
    "x": 68,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMassProductionFactoryColonial": {
    "x": 102,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMassProductionFactoryWarden": {
    "x": 136,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMedical": {
    "x": 170,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMedicalColonial": {
    "x": 204,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMedicalWarden": {
    "x": 238,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMortarHouse": {
    "x": 272,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMortarHouseColonial": {
    "x": 306,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconMortarHouseWarden": {
    "x": 340,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconObservationTower": {
    "x": 374,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconObservationTowerColonial": {
    "x": 408,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconObservationTowerWarden": {
    "x": 442,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconOilWell": {
    "x": 476,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconOilWellColonial": {
    "x": 510,
    "y": 136,
    "width": 32,
    "height": 32
  },
  "MapIconOilWellWarden": {
    "x": 0,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRelicBase": {
    "x": 34,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRelicBaseColonial": {
    "x": 68,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRelicBaseWarden": {
    "x": 102,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketGroundZero": {
    "x": 136,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketGroundZeroColonial": {
    "x": 170,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketGroundZeroWarden": {
    "x": 204,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSite": {
    "x": 238,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSiteColonial": {
    "x": 272,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSiteWarden": {
    "x": 306,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSiteWithRocket": {
    "x": 340,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSiteWithRocketColonial": {
    "x": 374,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketSiteWithRocketWarden": {
    "x": 408,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketTarget": {
    "x": 442,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketTargetColonial": {
    "x": 476,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconRocketTargetWarden": {
    "x": 510,
    "y": 170,
    "width": 32,
    "height": 32
  },
  "MapIconSafehouse": {
    "x": 0,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSafehouseColonial": {
    "x": 34,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSafehouseWarden": {
    "x": 68,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvage": {
    "x": 102,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvageColonial": {
    "x": 136,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvageMine": {
    "x": 170,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvageMineColonial": {
    "x": 204,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvageMineWarden": {
    "x": 238,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSalvageWarden": {
    "x": 272,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconScorchedTown": {
    "x": 306,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconScorchedTownColonial": {
    "x": 340,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconScorchedTownWarden": {
    "x": 374,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSeaport": {
    "x": 408,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSeaportColonial": {
    "x": 442,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconSeaportWarden": {
    "x": 476,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconShipyard": {
    "x": 510,
    "y": 204,
    "width": 32,
    "height": 32
  },
  "MapIconShipyardColonial": {
    "x": 0,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconShipyardWarden": {
    "x": 34,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase1": {
    "x": 68,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase1Colonial": {
    "x": 102,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase1Warden": {
    "x": 136,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase2": {
    "x": 170,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase2Colonial": {
    "x": 204,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase2Warden": {
    "x": 238,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase3": {
    "x": 272,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase3Colonial": {
    "x": 306,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStaticBase3Warden": {
    "x": 340,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStorageFacility": {
    "x": 374,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStorageFacilityColonial": {
    "x": 408,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStorageFacilityWarden": {
    "x": 442,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStormCannon": {
    "x": 476,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStormCannonColonial": {
    "x": 510,
    "y": 238,
    "width": 32,
    "height": 32
  },
  "MapIconStormCannonWarden": {
    "x": 0,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfur": {
    "x": 34,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfurColonial": {
    "x": 68,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfurMine": {
    "x": 102,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfurMineColonial": {
    "x": 136,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfurMineWarden": {
    "x": 170,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSulfurWarden": {
    "x": 204,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSupplies": {
    "x": 238,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSuppliesColonial": {
    "x": 272,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconSuppliesWarden": {
    "x": 306,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTechCenter": {
    "x": 340,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTechCenterColonial": {
    "x": 374,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTechCenterWarden": {
    "x": 408,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier1": {
    "x": 442,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier1Colonial": {
    "x": 476,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier1Warden": {
    "x": 510,
    "y": 272,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier2": {
    "x": 0,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier2Colonial": {
    "x": 34,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier2Warden": {
    "x": 68,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier3": {
    "x": 102,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier3Colonial": {
    "x": 136,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownBaseTier3Warden": {
    "x": 170,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownHall": {
    "x": 204,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownHallColonial": {
    "x": 238,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTownHallWarden": {
    "x": 272,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTroopShip": {
    "x": 306,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTroopShipColonial": {
    "x": 340,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconTroopShipWarden": {
    "x": 374,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconVehicle": {
    "x": 408,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconVehicleColonial": {
    "x": 442,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconVehicleWarden": {
    "x": 476,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconVictory": {
    "x": 510,
    "y": 306,
    "width": 32,
    "height": 32
  },
  "MapIconVictoryColonial": {
    "x": 0,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconVictoryWarden": {
    "x": 34,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWeatherStation": {
    "x": 68,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWeatherStationColonial": {
    "x": 102,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWeatherStationWarden": {
    "x": 136,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWorkshop": {
    "x": 170,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWorkshopColonial": {
    "x": 204,
    "y": 340,
    "width": 32,
    "height": 32
  },
  "MapIconWorkshopWarden": {
    "x": 238,
    "y": 340,
    "width": 32,
    "height": 32
  }
} as const;

// Helper to get CSS background-position
export function getIconSpritePosition(iconName: string): string {
  const coords = ICON_SPRITE_METADATA[iconName];
  if (!coords) return '0 0';
  return `-${coords.x}px -${coords.y}px`;
}

// Helper to get scaled CSS background-position for zoom levels
export function getIconSpritePositionScaled(iconName: string, scale: number): string {
  const coords = ICON_SPRITE_METADATA[iconName];
  if (!coords) return '0 0';
  const scaledX = coords.x * scale;
  const scaledY = coords.y * scale;
  return `-${scaledX}px -${scaledY}px`;
}

// Helper to check if icon exists in sprite
export function hasIconInSprite(iconName: string): boolean {
  return iconName in ICON_SPRITE_METADATA;
}

// Get all available icon names
export const AVAILABLE_ICONS = Object.keys(ICON_SPRITE_METADATA) as ReadonlyArray<string>;
